## set working directorty via set(wd)
datafull <- read.csv("household_power_consumption.txt", header=T, sep=';', na.strings="?",nrows=2075259, check.names=F, stringsAsFactors=F, comment.char="", quote='\"')
subdata1 <- subset(datafull, Date %in% c("1/2/2007","2/2/2007"))
subdata1$Date <- as.Date(subdata1$Date, format="%d/%m/%Y")
hist(subdata1$Global_active_power, main="Global Active Power",xlab="Global Active Power (kilowatts)", ylab="Frequency", col="Red")